# Enable or disable features that you dont need or want to use. This can help with performance and security.
modules:
  ec: false
  ecsee: false
  homes: false
  invsee: false
  pvptimer: false
  vanish: false



config:
