name: Coreon
version: '1.0.0'
main: at.blaulix.coreon.Coreon
api-version: '1.21'

commands:
  coreon:
    description: Coreon main command
    usage: /coreon
  invsee:
    description: Opens a player's inventory
    usage: /invsee <Player>
    permission: coreon.invsee
  vanish:
    description: Become invisible to other players
    usage: /vanish
    permission: coreon.vanish
  home:
    description: Gives you homes.
    usage: /home <Name>
    permission: coreon.homes.teleport
  homes:
    description: Lists your homes.
    usage: /homes <Playername>
    permission: coreon.homes.list
  sethome:
    description: Sets a home at your current position
    usage: /sethome <Name>
    permission: coreon.homes.set
  deletehome:
    description: Deletes a home
    usage: /delhome <Name>
    permission: coreon.homes.delete
  pvptimer:
    description: Sets a global PvP disable timer.
    usage: /pvptimer <minutes>
    permission: coreon.pvptimer
  ec:
    description: Opens your own enderchest
    usage: /ec
    permission: coreon.ec
  ecsee:
    description: Opens a player's enderchest
    usage: /ecsee <Player>
    permission: coreon.ecsee
