name: Coreon
version: '1.0.0'
main: at.blaulix.coreon.Coreon
api-version: '1.21'

commands:
  invsee:
    description: Öffnet das Inventar eines Spielers
    usage: /invsee <Spieler>
    permission: coreon.invsee